### PR TITLE
support #271

### PR DESCRIPTION
**Pull request by jinfahua**
The utility for setting docker system variables.

### CODE REVIEW

**Comment by jinfahua** [comment]
Will it add extra 3MB for the docker image? @zhanghongtong 
```shell
#  ls -lh deploy/docker/conf_util
-rwxr-xr-x  1 rockyjin  staff   3.0M May 25 21:33 deploy/docker/conf_util

```

**Comment by zhanghongtong** [comment]
> Will it add extra 3MB for the docker image? @zhanghongtong
> 
> ```shell
> #  ls -lh deploy/docker/conf_util
> -rwxr-xr-x  1 rockyjin  staff   3.0M May 25 21:33 deploy/docker/conf_util
> ```

Yes, the updated alpine image will be 22.6M, and the 0.4.0-alpine image will be 18.7M

**Comment by jinfahua** [comment]
> > Will it add extra 3MB for the docker image? @zhanghongtong
> > ```shell
> > #  ls -lh deploy/docker/conf_util
> > -rwxr-xr-x  1 rockyjin  staff   3.0M May 25 21:33 deploy/docker/conf_util
> > ```
> 
> Yes, the updated alpine image will be 22.6M, and the 0.4.0-alpine image will be 18.7M

Can you use upx to compress the binary file? @zhanghongtong

**Comment by zhanghongtong** [comment]
> > > Will it add extra 3MB for the docker image? @zhanghongtong
> > > ```shell
> > > #  ls -lh deploy/docker/conf_util
> > > -rwxr-xr-x  1 rockyjin  staff   3.0M May 25 21:33 deploy/docker/conf_util
> > > ```
> > 
> > 
> > Yes, the updated alpine image will be 22.6M, and the 0.4.0-alpine image will be 18.7M
> 
> Can you use upx to compress the binary file? @zhanghongtong

Yes, I compressed the binary file using upx, the alpine image is only 20.7 M

**Comment by jinfahua** [comment]
@zhanghongtong Cool!

**Pull request merged**
